// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRIVHtCvLCA1FCyTZypvAfzc7odOk7Wz4',
    appId: '1:896900769145:web:2b4c69096331e2f743bba8',
    messagingSenderId: '896900769145',
    projectId: 'xyzride',
    authDomain: 'xyzride.firebaseapp.com',
    storageBucket: 'xyzride.appspot.com',
    measurementId: 'G-M2N65LQNMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZja7Y_JPeKDwhNYK9PgD8Icuv1Kq8xw',
    appId: '1:896900769145:android:2a679521ae52f42b43bba8',
    messagingSenderId: '896900769145',
    projectId: 'xyzride',
    storageBucket: 'xyzride.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGPgY02433QlcpYp7v8u2FTaPoZ0SRoE',
    appId: '1:896900769145:ios:ecb11d4637c4958f43bba8',
    messagingSenderId: '896900769145',
    projectId: 'xyzride',
    storageBucket: 'xyzride.appspot.com',
    iosClientId:
        '896900769145-b3brbc17vv560ffhkfp7i55ni9431okn.apps.googleusercontent.com',
    iosBundleId: 'com.example.xyzRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPGPgY02433QlcpYp7v8u2FTaPoZ0SRoE',
    appId: '1:896900769145:ios:ecb11d4637c4958f43bba8',
    messagingSenderId: '896900769145',
    projectId: 'xyzride',
    storageBucket: 'xyzride.appspot.com',
    iosClientId:
        '896900769145-b3brbc17vv560ffhkfp7i55ni9431okn.apps.googleusercontent.com',
    iosBundleId: 'com.example.xyzRide',
  );
}
// Platform  Firebase App Id
// web       1:896900769145:web:2b4c69096331e2f743bba8
// android   1:896900769145:android:2a679521ae52f42b43bba8
// ios       1:896900769145:ios:ecb11d4637c4958f43bba8
// macos     1:896900769145:ios:ecb11d4637c4958f43bba8